import JSZip from "jszip";

export interface ShopifyExportResult {
  zipBlob: Blob;
  fileName: string;
}

export async function compileShopifyLiquidTheme(
  projectId: string,
  htmlContent: string,
  cssContent: string
): Promise<ShopifyExportResult> {
  const zip = new JSZip();

  // 1. Layout directory
  const themeLiquid = `<!doctype html>
<html class="no-js" lang="{{ request.locale.iso_code }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{{ page_title }} - {{ shop.name }}</title>
    {{ content_for_header }}
    <script src="https://cdn.tailwindcss.com"></script>
    {{ 'theme.css' | asset_url | stylesheet_tag }}
  </head>
  <body class="bg-slate-50 text-slate-900 font-sans antialiased">
    {% section 'header' %}
    <main id="MainContent" role="main" tabindex="-1">
      {{ content_for_layout }}
    </main>
    {% section 'footer' %}
  </body>
</html>`;

  zip.file("layout/theme.liquid", themeLiquid);

  // 2. Templates directory
  const indexJson = JSON.stringify(
    {
      sections: {
        announcement_bar: { type: "announcement-bar" },
        header: { type: "header" },
        hero: { type: "hero" },
        featured_products: { type: "featured-products" },
        features: { type: "features" },
        reviews: { type: "reviews" },
        footer: { type: "footer" }
      },
      order: [
        "announcement_bar",
        "header",
        "hero",
        "featured_products",
        "features",
        "reviews",
        "footer"
      ],
    },
    null,
    2
  );
  zip.file("templates/index.json", indexJson);

  // 3. Sections directory
  const headerSection = `{% comment %} Shopify Header Section generated by StitchStore AI {% endcomment %}
<header class="bg-white border-b border-slate-200 py-4 px-6 sticky top-0 z-50">
  <div class="max-w-6xl mx-auto flex items-center justify-between">
    <a href="/" class="text-xl font-bold text-slate-900 flex items-center gap-2">
      <span>{{ shop.name | default: 'StitchStore' }}</span>
    </a>
    <nav class="hidden md:flex items-center gap-6 text-sm font-medium text-slate-600">
      {% for link in linklists.main-menu.links %}
        <a href="{{ link.url }}" class="hover:text-rose-600 transition-colors">{{ link.title }}</a>
      {% else %}
        <a href="/" class="hover:text-rose-600 transition-colors">Home</a>
        <a href="/collections/all" class="hover:text-rose-600 transition-colors">Catalog</a>
      {% endfor %}
    </nav>
  </div>
</header>

{% schema %}
{
  "name": "Header",
  "settings": [],
  "presets": [{ "name": "Header" }]
}
{% endschema %}`;

  const footerSection = `{% comment %} Shopify Footer Section generated by StitchStore AI {% endcomment %}
<footer class="bg-slate-50 border-t border-slate-200 py-12 px-6 text-slate-500 text-sm">
  <div class="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
    <p>&copy; {{ 'now' | date: "%Y" }} {{ shop.name | default: 'StitchStore' }}. All rights reserved.</p>
    <div class="flex items-center gap-6">
      <a href="/policies/privacy-policy" class="hover:text-slate-900 transition-colors">Privacy</a>
      <a href="/policies/terms-of-service" class="hover:text-slate-900 transition-colors">Terms</a>
    </div>
  </div>
</footer>

{% schema %}
{
  "name": "Footer",
  "settings": [],
  "presets": [{ "name": "Footer" }]
}
{% endschema %}`;

  const heroSection = `{% comment %} Shopify Hero Section generated by StitchStore AI {% endcomment %}
<section class="relative bg-slate-50 py-20 px-6 text-center border-b border-slate-200">
  <div class="max-w-4xl mx-auto space-y-6">
    <h1 class="text-4xl sm:text-6xl font-extrabold text-slate-900 tracking-tight">
      {{ section.settings.heading | default: 'Elevate Your Style' }}
    </h1>
    <p class="text-slate-500 text-lg max-w-2xl mx-auto">
      {{ section.settings.subheading | default: 'Discover luxury curated collections powered by Liquid 2.0.' }}
    </p>
    <a href="{{ section.settings.button_link | default: '/collections/all' }}" class="inline-flex items-center justify-center px-6 py-3 rounded-xl bg-rose-600 hover:bg-rose-700 text-white font-semibold shadow-lg shadow-rose-600/20 transition-all">
      {{ section.settings.button_text | default: 'Shop Collection' }}
    </a>
  </div>
</section>

{% schema %}
{
  "name": "Hero Banner",
  "settings": [
    { "type": "text", "id": "heading", "label": "Heading", "default": "Elevate Your Style" },
    { "type": "text", "id": "subheading", "label": "Subheading", "default": "Discover luxury curated collections" },
    { "type": "text", "id": "button_text", "label": "Button Text", "default": "Shop Collection" },
    { "type": "url", "id": "button_link", "label": "Button Link" }
  ],
  "presets": [{ "name": "Hero Banner" }]
}
{% endschema %}`;

  const featuredProductsSection = `{% comment %} Shopify Featured Products Section generated by StitchStore AI {% endcomment %}
<section class="py-16 px-6 max-w-6xl mx-auto">
  <h2 class="text-2xl font-bold text-slate-900 mb-8 flex items-center gap-2">
    <span>✨ Featured Collection</span>
  </h2>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6">
    {% for product in collections.frontpage.products limit: 4 %}
      {% render 'product-card', product: product %}
    {% else %}
      <div class="col-span-full p-8 rounded-xl border border-slate-200 bg-white/80 text-center text-slate-500">
        No products available in Frontpage collection.
      </div>
    {% endfor %}
  </div>
</section>

{% schema %}
{
  "name": "Featured Products",
  "settings": [],
  "presets": [{ "name": "Featured Products" }]
}
{% endschema %}`;

  zip.file("sections/header.liquid", headerSection);
  zip.file("sections/footer.liquid", footerSection);
  zip.file("sections/hero.liquid", heroSection);
  zip.file("sections/featured-products.liquid", featuredProductsSection);

  // 4. Snippets directory
  const productCardSnippet = `<div class="group rounded-xl border border-slate-200 bg-white p-4 hover:border-slate-300 transition-all">
  <div class="aspect-square bg-slate-200 rounded-lg overflow-hidden mb-3 relative">
    <img src="{{ product.featured_image | image_url: width: 400 }}" alt="{{ product.title }}" class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" />
  </div>
  <h3 class="text-sm font-semibold text-slate-900 group-hover:text-rose-600 transition-colors">
    <a href="{{ product.url }}">{{ product.title }}</a>
  </h3>
  <p class="text-xs font-mono text-emerald-600 mt-1">{{ product.price | money }}</p>
</div>`;

  zip.file("snippets/product-card.liquid", productCardSnippet);

  // 5. Assets directory
  const compiledCss = cssContent || `/* Global Theme CSS compiled by StitchStore AI */
body { background-color: #f8fafc; color: #0f172a; }
.glass-panel { background: rgba(255, 255, 255, 0.85); backdrop-filter: blur(12px); }
`;
  zip.file("assets/theme.css", compiledCss);

  // 6. Raw HTML export copy inside asset for backup reference
  zip.file("assets/raw_source.html", htmlContent);

  const safeId = projectId.replace(/[^a-zA-Z0-9_-]/g, "_");
  const zipBlob = await zip.generateAsync({ type: "blob" });
  return {
    zipBlob,
    fileName: `${safeId}-shopify-theme.zip`,
  };
}
