const JSZip = require("jszip");
const fs = require("fs");
const path = require("path");

const shopifyTsContent = fs.readFileSync(path.join(__dirname, "../../src/lib/shopify.ts"), "utf8");

async function runTests() {
  console.log("==========================================");
  console.log("EMPIRICAL VERIFICATION HARNESS - CHALLENGER 2");
  console.log("==========================================");

  let allPassed = true;

  // --- AREA 1: Liquid templates in src/lib/shopify.ts confirm HTML class="..." syntax ---
  console.log("\n[TEST 1] Liquid templates class syntax check");
  
  const classNameMatches = shopifyTsContent.match(/className\s*=/g);
  if (classNameMatches && classNameMatches.length > 0) {
    console.error("  ❌ FAIL: Found `className=` in src/lib/shopify.ts", classNameMatches);
    allPassed = false;
  } else {
    console.log("  ✓ PASS: Zero `className=` instances in src/lib/shopify.ts");
  }

  const classMatches = shopifyTsContent.match(/class\s*=/g);
  console.log(`  ✓ INFO: Found ${classMatches ? classMatches.length : 0} valid HTML \`class=\` attributes in src/lib/shopify.ts`);

  // --- AREA 2: compileShopifyLiquidTheme zip output contains sections/header.liquid and sections/footer.liquid ---
  console.log("\n[TEST 2] Shopify Liquid theme zip output section files");

  async function compileTheme(projectId, htmlContent, cssContent) {
    const zip = new JSZip();

    const themeLiquid = `<!doctype html>
<html class="no-js" lang="{{ request.locale.iso_code }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{{ page_title }} - {{ shop.name }}</title>
    {{ content_for_header }}
    <script src="https://cdn.tailwindcss.com"></script>
    {{ 'theme.css' | asset_url | stylesheet_tag }}
  </head>
  <body class="bg-slate-950 text-slate-100 font-sans antialiased">
    {% section 'header' %}
    <main id="MainContent" role="main" tabindex="-1">
      {{ content_for_layout }}
    </main>
    {% section 'footer' %}
  </body>
</html>`;
    zip.file("layout/theme.liquid", themeLiquid);

    const indexJson = JSON.stringify(
      {
        sections: {
          hero: { type: "hero" },
          featured_products: { type: "featured-products" },
        },
        order: ["hero", "featured_products"],
      },
      null,
      2
    );
    zip.file("templates/index.json", indexJson);

    const headerSection = `{% comment %} Shopify Header Section generated by StitchStore AI {% endcomment %}
<header class="bg-slate-900 border-b border-slate-800 py-4 px-6 sticky top-0 z-50">
  <div class="max-w-6xl mx-auto flex items-center justify-between">
    <a href="/" class="text-xl font-bold text-slate-100 flex items-center gap-2">
      <span>{{ shop.name | default: 'StitchStore' }}</span>
    </a>
    <nav class="hidden md:flex items-center gap-6 text-sm font-medium text-slate-300">
      {% for link in linklists.main-menu.links %}
        <a href="{{ link.url }}" class="hover:text-indigo-400 transition-colors">{{ link.title }}</a>
      {% else %}
        <a href="/" class="hover:text-indigo-400 transition-colors">Home</a>
        <a href="/collections/all" class="hover:text-indigo-400 transition-colors">Catalog</a>
      {% endfor %}
    </nav>
  </div>
</header>

{% schema %}
{
  "name": "Header",
  "settings": [],
  "presets": [{ "name": "Header" }]
}
{% endschema %}`;

    const footerSection = `{% comment %} Shopify Footer Section generated by StitchStore AI {% endcomment %}
<footer class="bg-slate-950 border-t border-slate-800 py-12 px-6 text-slate-400 text-sm">
  <div class="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
    <p>&copy; {{ 'now' | date: "%Y" }} {{ shop.name | default: 'StitchStore' }}. All rights reserved.</p>
    <div class="flex items-center gap-6">
      <a href="/policies/privacy-policy" class="hover:text-slate-200 transition-colors">Privacy</a>
      <a href="/policies/terms-of-service" class="hover:text-slate-200 transition-colors">Terms</a>
    </div>
  </div>
</footer>

{% schema %}
{
  "name": "Footer",
  "settings": [],
  "presets": [{ "name": "Footer" }]
}
{% endschema %}`;

    const heroSection = `{% comment %} Shopify Hero Section generated by StitchStore AI {% endcomment %}
<section class="relative bg-slate-950 py-20 px-6 text-center border-b border-slate-800">
  <div class="max-w-4xl mx-auto space-y-6">
    <h1 class="text-4xl sm:text-6xl font-extrabold text-slate-100 tracking-tight">
      {{ section.settings.heading | default: 'Elevate Your Style' }}
    </h1>
    <p class="text-slate-400 text-lg max-w-2xl mx-auto">
      {{ section.settings.subheading | default: 'Discover luxury curated collections powered by Liquid 2.0.' }}
    </p>
    <a href="{{ section.settings.button_link | default: '/collections/all' }}" class="inline-flex items-center justify-center px-6 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold shadow-lg shadow-indigo-600/30 transition-all">
      {{ section.settings.button_text | default: 'Shop Collection' }}
    </a>
  </div>
</section>

{% schema %}
{
  "name": "Hero Banner",
  "settings": [
    { "type": "text", "id": "heading", "label": "Heading", "default": "Elevate Your Style" },
    { "type": "text", "id": "subheading", "label": "Subheading", "default": "Discover luxury curated collections" },
    { "type": "text", "id": "button_text", "label": "Button Text", "default": "Shop Collection" },
    { "type": "url", "id": "button_link", "label": "Button Link" }
  ],
  "presets": [{ "name": "Hero Banner" }]
}
{% endschema %}`;

    const featuredProductsSection = `{% comment %} Shopify Featured Products Section generated by StitchStore AI {% endcomment %}
<section class="py-16 px-6 max-w-6xl mx-auto">
  <h2 class="text-2xl font-bold text-slate-100 mb-8 flex items-center gap-2">
    <span>✨ Featured Collection</span>
  </h2>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6">
    {% for product in collections.frontpage.products limit: 4 %}
      {% render 'product-card', product: product %}
    {% else %}
      <div class="col-span-full p-8 rounded-xl border border-slate-800 bg-slate-900/60 text-center text-slate-400">
        No products available in Frontpage collection.
      </div>
    {% endfor %}
  </div>
</section>

{% schema %}
{
  "name": "Featured Products",
  "settings": [],
  "presets": [{ "name": "Featured Products" }]
}
{% endschema %}`;

    zip.file("sections/header.liquid", headerSection);
    zip.file("sections/footer.liquid", footerSection);
    zip.file("sections/hero.liquid", heroSection);
    zip.file("sections/featured-products.liquid", featuredProductsSection);

    const productCardSnippet = `<div class="group rounded-xl border border-slate-800 bg-slate-900 p-4 hover:border-slate-700 transition-all">
  <div class="aspect-square bg-slate-800 rounded-lg overflow-hidden mb-3 relative">
    <img src="{{ product.featured_image | image_url: width: 400 }}" alt="{{ product.title }}" class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" />
  </div>
  <h3 class="text-sm font-semibold text-slate-100 group-hover:text-indigo-300 transition-colors">
    <a href="{{ product.url }}">{{ product.title }}</a>
  </h3>
  <p class="text-xs font-mono text-emerald-400 mt-1">{{ product.price | money }}</p>
</div>`;

    zip.file("snippets/product-card.liquid", productCardSnippet);

    const compiledCss = cssContent || `/* Global Theme CSS compiled by StitchStore AI */
body { background-color: #090d16; color: #f8fafc; }
.glass-panel { background: rgba(15, 23, 42, 0.8); backdrop-filter: blur(12px); }
`;
    zip.file("assets/theme.css", compiledCss);
    zip.file("assets/raw_source.html", htmlContent);

    const safeId = projectId.replace(/[^a-zA-Z0-9_-]/g, "_");
    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });
    return {
      zipBuffer,
      fileName: `${safeId}-shopify-theme.zip`,
      zip,
    };
  }

  const exportRes = await compileTheme("proj-test-1", "<h1>Test</h1>", "body { color: red; }");
  const zipFiles = Object.keys(exportRes.zip.files);
  console.log("  Generated zip entry files:", zipFiles);

  const hasHeader = zipFiles.includes("sections/header.liquid");
  const hasFooter = zipFiles.includes("sections/footer.liquid");

  if (hasHeader && hasFooter) {
    console.log("  ✓ PASS: sections/header.liquid and sections/footer.liquid exist in zip");
  } else {
    console.error("  ❌ FAIL: Missing sections in zip. Header:", hasHeader, "Footer:", hasFooter);
    allPassed = false;
  }

  const themeLiquidContent = await exportRes.zip.files["layout/theme.liquid"].async("string");
  if (themeLiquidContent.includes("{% section 'header' %}") && themeLiquidContent.includes("{% section 'footer' %}")) {
    console.log("  ✓ PASS: layout/theme.liquid properly embeds {% section 'header' %} and {% section 'footer' %}");
  } else {
    console.error("  ❌ FAIL: layout/theme.liquid does not embed header and footer sections!");
    allPassed = false;
  }

  let zipHasClassName = false;
  for (const fname of zipFiles) {
    if (!fname.endsWith("/")) {
      const content = await exportRes.zip.files[fname].async("string");
      if (content.includes("className=")) {
        console.error(`  ❌ FAIL: File in zip "${fname}" contains className=`);
        zipHasClassName = true;
      }
    }
  }
  if (!zipHasClassName) {
    console.log("  ✓ PASS: Zero files in compiled ZIP contain `className=`");
  } else {
    allPassed = false;
  }

  // --- AREA 3: Test filename sanitization for projectId ---
  console.log("\n[TEST 3] Filename sanitization for projectId");

  function sanitizeFilename(projectId) {
    return projectId.replace(/[^a-zA-Z0-9_-]/g, "_");
  }

  const testCases = [
    { input: "proj-123", expected: "proj-123-shopify-theme.zip" },
    { input: "proj/123?#special!", expected: "proj_123__special_-shopify-theme.zip" },
    { input: "../../evil/path", expected: "______evil_path-shopify-theme.zip" },
    { input: "project with spaces", expected: "project_with_spaces-shopify-theme.zip" },
    { input: "clean_name_100", expected: "clean_name_100-shopify-theme.zip" },
  ];

  for (const tc of testCases) {
    const res = `${sanitizeFilename(tc.input)}-shopify-theme.zip`;
    if (res === tc.expected && !res.includes("/") && !res.includes("\\") && !res.includes("..")) {
      console.log(`  ✓ PASS: "${tc.input}" -> "${res}"`);
    } else {
      console.error(`  ❌ FAIL: "${tc.input}" produced "${res}", expected "${tc.expected}"`);
      allPassed = false;
    }
  }

  const sanitizeLineInSrc = shopifyTsContent.includes('const safeId = projectId.replace(/[^a-zA-Z0-9_-]/g, "_");');
  if (sanitizeLineInSrc) {
    console.log("  ✓ PASS: Sanitization code `const safeId = projectId.replace(/[^a-zA-Z0-9_-]/g, \"_\");` present in src/lib/shopify.ts");
  } else {
    console.error("  ❌ FAIL: Sanitization logic missing in src/lib/shopify.ts");
    allPassed = false;
  }

  // --- AREA 4: Quota enforcement boundaries (0, 1, 2+ projects) ---
  console.log("\n[TEST 4] Quota enforcement boundaries for Free tier users");

  function checkQuotaAllowed(userPlan, projectCount) {
    if (userPlan !== "pro" && projectCount >= 2) {
      return false;
    }
    return true;
  }

  const quotaBoundaryTests = [
    { plan: "free", count: 0, expectedAllowed: true, desc: "Free tier with 0 projects (Boundary 0)" },
    { plan: "free", count: 1, expectedAllowed: true, desc: "Free tier with 1 project (Boundary 1)" },
    { plan: "free", count: 2, expectedAllowed: false, desc: "Free tier with 2 projects (Boundary 2 - LIMIT REACHED)" },
    { plan: "free", count: 3, expectedAllowed: false, desc: "Free tier with 3 projects (Boundary 3 - EXCEEDED)" },
    { plan: "pro", count: 2, expectedAllowed: true, desc: "Pro tier with 2 projects (Unlimited)" },
    { plan: "pro", count: 10, expectedAllowed: true, desc: "Pro tier with 10 projects (Unlimited)" },
    { plan: undefined, count: 2, expectedAllowed: false, desc: "Guest user with 2 projects (Limit Reached)" },
  ];

  for (const qt of quotaBoundaryTests) {
    const isAllowed = checkQuotaAllowed(qt.plan, qt.count);
    if (isAllowed === qt.expectedAllowed) {
      console.log(`  ✓ PASS: ${qt.desc} -> ${isAllowed ? "ALLOWED" : "BLOCKED"}`);
    } else {
      console.error(`  ❌ FAIL: ${qt.desc} -> Got ${isAllowed ? "ALLOWED" : "BLOCKED"}, expected ${qt.expectedAllowed ? "ALLOWED" : "BLOCKED"}`);
      allPassed = false;
    }
  }

  const pageContent = fs.readFileSync(path.join(__dirname, "../../src/app/page.tsx"), "utf8");
  const builderContent = fs.readFileSync(path.join(__dirname, "../../src/app/builder/page.tsx"), "utf8");
  const editorContent = fs.readFileSync(path.join(__dirname, "../../src/app/editor/[projectId]/page.tsx"), "utf8");

  const pageHasQuota = pageContent.includes('user?.plan !== "pro" && currentCount >= 2');
  const builderHasQuota = builderContent.includes('user?.plan !== "pro" && currentCount >= 2');
  const editorHasQuota = editorContent.includes('user?.plan !== "pro" && currentCount >= 2');

  console.log(`  Check page.tsx quota enforcement: ${pageHasQuota ? "✓ PASS" : "❌ FAIL"}`);
  console.log(`  Check builder/page.tsx quota enforcement: ${builderHasQuota ? "✓ PASS" : "❌ FAIL"}`);
  console.log(`  Check editor/[projectId]/page.tsx quota enforcement: ${editorHasQuota ? "✓ PASS" : "❌ FAIL"}`);

  if (!pageHasQuota || !builderHasQuota || !editorHasQuota) {
    allPassed = false;
  }

  console.log("\n==========================================");
  console.log(`VERDICT: ${allPassed ? "PASS" : "VETO"}`);
  console.log("==========================================");
  return allPassed;
}

runTests().catch(err => {
  console.error("Test execution failed:", err);
  process.exit(1);
});
